version: '3.8'

services:
  mongo:
    build:
      context: ./docker
      dockerfile: Dockerfile.mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: forms_db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sveltekit-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo
    command: sh -c "npm run build && npm run preview -- --port 3000 --host"


volumes:
  mongo-data:
